### PR TITLE
Fix parsing of output flag

### LINKED ISSUE #2: `-o` option is ignored
First of all, thanks a lot for this repo, that is exactly what we needed!

At the moment, it seems like the option `-o`, which should specify an output folder, is currently ignored by the script.

### PR DESCRIPTION
**Pull request by Siedlerchr**
I was stumbling across this issue today and found it the value of output Flag is ignored and the fix is just one line

Fixes https://github.com/GoogleCloudPlatform/proto-gen-md-diagrams/issues/2

### CODE REVIEW

**Comment by chicco785** [comment]
@rrmcguinness @Siedlerchr this PR probably changed substantially the original behaviour, and I am not sure there is a way to have it back. before last changes, when I was passing a directory with `-d` as proto source the `md` files were generated in the same directory as the protobuffer files, now, regardless the protobuf folder hierarchy, they are all generated in the `.` folder.

**Comment by Siedlerchr** [comment]
Not sure I understand your problem. My commit only fixed the -o flag beeing ignored, nothing else. So I guess you have to specify the output flag now

**Comment by chicco785** [comment]
The behaviour changed substantially. Before, not passing any parameter, the hierarchy was respected.

If had a structure like:
```
- folder1
  - folder2
    - 1.proto
  - folder3
    - 2.proto  
```

the output would have been:
```
- folder1
  - folder2
    - 1.md
  - folder3
    - 2.md  
```

Now, even passing the `-o folder1` parameter, the result is:
```
- folder1
  - 1.md
  - 2.md  
```

**Comment by Siedlerchr** [comment]
Ah I see, thanks, I think I know what caused the problem, will try to fix it later.

**Pull request merged**
